# Generated by Django 5.0.6 on 2024-06-24 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_date_event_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='data',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='descricao',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='local',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='event',
            name='nome',
        ),
    ]
